### ISSUE TITLE
Hardcoded values together with variables

### ISSUE THREAD

**Issue by chfuchte** [chfuchte/ws-artnet-controller#4]
```yaml
    - identifier: effect2{1}
      mode: alternate
      steps:
      - delay: 0
        actions:
          - par64_1.White: "{1}"
      - delay: 1000
        actions:
          - par64_1.White: 0
```

this does not work as it tries to interpret `0` as a variable
